# Generated by Django 3.2.3 on 2021-05-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herokuapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_img',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
