# Generated by Django 3.2.3 on 2021-05-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herokuapp', '0002_movie_movie_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
