# Generated by Django 3.2.3 on 2021-05-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herokuapp', '0003_alter_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='youtube_url',
            field=models.URLField(default='https://www.youtube.com/watch?v=6Jg_rkKtJgo'),
        ),
    ]
